name: Generate Contribution Snake

on:
  schedule:
    # Atualiza diariamente
    - cron: "0 1 * * *"

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}

          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%2300E7FF&color_dots=%23161B22,%230D5661,%230096A8,%2300C6DE,%2300E7FF
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%2300E7FF

      - name: Publish snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
